# Generated by Django 4.1.2 on 2022-12-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_interest_user_fields_of_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
