# Generated by Django 4.1.2 on 2022-12-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room_id',
            field=models.IntegerField(null=True),
        ),
    ]
