# Generated by Django 4.1.2 on 2022-12-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(max_length=20),
        ),
    ]
